name: CICD

on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, synchronize, closed ]

env:
  BRANCH_NAME: "${{ github.head_ref }}"

jobs:
  if_opened_or_pushed_to:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            pipeline_dir="${BRANCH_NAME%%/*}"
            if [ -d "$pipeline_dir/" ]; then
              cd "$pipeline_dir"
              az deployment group create -g bicpoc-rg-test \
                --template-file BICPOCFactory.json \
                --parameters @ParametersTest.json
            else
              echo "***************************** SKIPPING DEPLOY ******************************"
              echo "Branch prefix '$pipeline_dir' does not represent a pipeline directory."
              echo "****************************************************************************"
            fi

  if_merged:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            pipeline_dir="${BRANCH_NAME%%/*}"
            if [ -d "$pipeline_dir/" ]; then
              cd "$pipeline_dir"
              az deployment group create -g bicpoc-rg-production \
                --template-file BICPOCFactory.json \
                --parameters @ParametersProduction.json
            else
              echo "***************************** SKIPPING DEPLOY ******************************"
              echo "Branch prefix '$pipeline_dir' does not represent a pipeline directory."
              echo "****************************************************************************"
            fi
