name: CICD

on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, synchronize, closed ]

env:
  BRANCH_NAME: "${{ github.ref_name }}"

jobs:
  if_opened_or_pushed_to:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Choose Folder
        run: |
          if [ -d "$BRANCH_NAME/" ]; then
            cd "${$BRANCH_NAME%%/*}"
          else
            echo "Pipeline Does not exist!"
            exit 1
          fi

      - name: Test
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: bicpoc-rg-development
          template: ./ARMTemplateForBICPOCFactory.json
          parameters: ./ARMTemplateParametersForBICPOCFactory.json
          additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"

  if_merged:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Choose Folder
        run: |
          if [ -d "$BRANCH_NAME/" ]; then
            cd "${$BRANCH_NAME%%/*}"
          else
            echo "Pipeline Does not exist!"
            exit 1
          fi

      - name: Test
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: bicpoc-rg-test
          template: ./bicpoc/ARMTemplateForBICPOCFactory.json
          parameters: ./bicpoc/ARMTemplateParametersForBICPOCFactory.json
          additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
