name: CICD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  arm-deploy:
    name: ARM Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Test
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: bicpoc-rg-development
          template: ./bicpoc/ARMTemplateForBICPOCFactory.json
          parameters: ./bicpoc/ARMTemplateParametersForBICPOCFactory.json
          additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
